### ISSUE TITLE
Class vs Instance methods

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip#1]
@AliSoftware Why you've decided to use class methods in stead of having different instances of containers? Is it intentional design decision?

**Comment by AliSoftware** [comment]
Good question sir!

The aim was to be able to do `Dependency.resolve()` anywhere in the app. If it were instance methods you'd need to have access to that instance anywhere in the app or pass it by reference everywhere, which I wanted to avoid. Or have a `sharedInstance` for the `Dependency` container but that would defeat the purpose.

I'm open to suggestions so that you can still use

**Comment by AliSoftware** [comment]
(Woops realized I closed this by mistake, sorry)

**Comment by AliSoftware** [comment]
@ilyapuchka I just made a branch starting to implement your suggestion.

What do you think of this new solution? I think it's really nice, but would be interested in your feedback.

(If it fits what you had in mind, I'll need to update the README to reflect this change too)

**Comment by ilyapuchka** [comment]
@AliSoftware I think it's absolutely fine =) Why I suggested that is that (as for me) referencing class is the same as referencing it's shared instance, it's still tightly coupling. With instance methods we also can inject containers themselves, which could be handy.

**Comment by AliSoftware** [comment]
True, that was a very good suggestion, thx! :+1:

Closing this issue and will keep the PR open until I update the README accordingly
