### ISSUE TITLE
Problem using type alias & tuples as Resolve Parameter

### ISSUE THREAD

**Issue by vander2675** [AliSoftware/Dip#147]
I had working code till the Xcode update yesterday.

```Swift
container.register() {(credentials: LoginCredentials) in
            try Login(credentials: credentials, validation: self.container.resolve(), request: self.container.resolve(), persist: self.container.resolve()) as Login
        }

    func resolveLogin(credentials: LoginCredentials) -> Login {
        return try! container.resolve(arguments: credentials) as Login
    }
```
This was working great. Login Credentials was a type alias for `(String, String)` Tuple.

Starting today it results in a Runtime crash:
No definition registered for type: Login, arguments: (email : String, password : String), tag: nil.

When I change the resolve to:
```Swift
    func resolveLogin(credentials: LoginCredentials) -> Login {
        return try! container.resolve(arguments: (credentials.email, credentials.password)) as Login
    }
```

It's working again

**Comment by ilyapuchka** [comment]
I will look at that later to figure out what changes in Swift 3.1 might have caused that and if that is a bug.
Currently there are different ways to workaround that: you can either do what you do, or you can cast result of `register` call to `Definition<Login, LoginCredentials>`, or you can resolve it like `resolve(arguments: email, password)`

**Comment by ilyapuchka** [comment]
It feels like registering factories with tuple arguments was not working correctly in swift 3 too. What happens is that `register` call incorrectly infers its generic parameters and calls the variant for factory that accepts two parameters instead of one. But at the same time  I guess it might be connected with this proposal https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md
According to [CHANGELOG](https://github.com/apple/swift/blob/master/CHANGELOG.md) it should be already implemented for swift 4

**Comment by ilyapuchka** [comment]
According to [this thread](https://twitter.com/ilyapuchka/status/851914287471894529) the issue addressed by SE-0110 should be fixed in swift 4. Though issue with type aliases still can be something different. I will close this and will reference it in #107
