### ISSUE TITLE
Register with Scope and Tag & Register Generic Classes

### ISSUE THREAD

**Issue by vander2675** [AliSoftware/Dip#162]
I've got a Problem with registering a Class with a Tag and a Scope. I can't find the right `register`Method for it.

What I want to do:
```swift
            container.register(.uniqe, tag: EntityType.User) {
                PutImpl<User>(backgroundContext: try container.resolve())
            }
```
Wich is not possible. Is there a correct `register`Method for this kind of Registration?

And while I'm at it:
Is this (using Tags) how you would resolve a particular Instance of an Generic Class with DI?
Thank you very much for your help. Still getting into DI.

**Comment by ilyapuchka** [comment]
I'm not sure I understand why you can not find a method that registers with scope and tag at the same time - all register methods accept scope and tag parameters. Does your tag type conform to `DependencyTagConvertible`? And you should resolve your component with `container.resolve() as PutImpl<User>`

Different containers approach resolving generic types in different ways, sometimes it's dictated by language features. i.e. in C# [di containers](https://github.com/castleproject/Windsor/blob/master/docs/registering-components-one-by-one.md#to-register-a-generic-type) you can skip providing generic parameters when registering generic type because C# support "open generics". This is not something that is possible in Swift.

**Comment by vander2675** [comment]
Okay Thank you very much. 
Is it possible to register a generic Class once and resolve it with multiple Instances?

**Comment by ilyapuchka** [comment]
You register it with `unique` scope just like other types. For container the generic nature of the type does not matter, you register it as `PutImpl<User>` and you resolve it as `PutImpl<User>`.
