### ISSUE TITLE
Publish version 7.1.0 to CocoaPods

### ISSUE THREAD

**Issue by michalsrutek** [AliSoftware/Dip#234]
Hi, thanks a great DI container!

It seems like you might have forgotten to push the newest version (7.1.0) to CocoaPods, could you do that? :)

Thanks!

**Comment by ilyapuchka** [comment]
It's not possible unfortunately ATM as cocoapods trunk does not authorise emails with custom domains, so I can't register with my email and changing author does not simply change the owner of the spec. So unless @AliSoftware will manage to authorise with trunk and push it or change owners of the spec somehow, everyone will have to use master branch.

**Comment by AliSoftware** [comment]
@ilyapuchka You're listed as a owner of the Pod in trunk (alongside with me) though (see `pod trunk info Dip`), so you should be able to push with it 🤔

I can add you again with a different email if you have trouble registering to trunk with your custom one, but I find it odd that you wouldn't be able to register, as I'm using a custom domain for my email too, same as you, but managed to register just right now without an issue… (maybe check your spam folder for the confirmation email?)

Anyway, I've tried to push 7.1.0 and 7.1.1 to CocoaPods, but the `swift_version` in the `pod spec` for those tags seem to be invalid (even though I used `bundle exec` to use the version of CocoaPods declared in Dip's Gemfile):

```
~/Documents/Dev/GitHub/Dip on  3b2f5a2 ⌚ 19:39:43
$ bundle exec pod trunk push Dip.podspec                                                                                                                                                                                ‹ruby-2.6.4›
Updating spec repo `master`

CocoaPods 1.9.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.0.beta.2

Validating podspec
 -> Dip (7.1.0)
    - ERROR | attributes: Unacceptable type `Array` for `swift_version`. Allowed values: `[String]`.
    - ERROR | attributes: Unable to validate `swift_version` (Malformed version number string ["5.0", "5.1"]).
    - ERROR | [iOS] unknown: Encountered an unknown error (The `Dip` pod failed to validate due to 2 errors:
    - ERROR | attributes: Unacceptable type `Array` for `swift_version`. Allowed values: `[String]`.
    - ERROR | attributes: Unable to validate `swift_version` (Malformed version number string ["5.0", "5.1"]).

) during validation.

[!] The spec did not pass validation, due to 3 errors.
```

This might be due to the fact that Dip still declares to use CocoaPods 1.4.0 in the `Gemfile`, so you need to update the `Gemfile` to update ideally to CP 1.8.4+ and potentially fix the `podspec` too before you can `pod trunk push` those versions; since you've already tagged those, I'll let you decide if you want to move the tags, create separate tags fixing those, or skip to a 7.1.2 fixing those.

**Comment by michalsrutek** [comment]
@ilyapuchka  @AliSoftware  Any update on this, guys? Were you able to resolve the Cocoapods email issue?

**Comment by max-potapov** [comment]
Dip just passed all checks with CocoaPods 1.9.0. All we need is update `Gemfile` to latest release of CocoaPods.

**Comment by ilyapuchka** [comment]
This is unfortunately still an issue with Cocoapods 1.9.1
> [!] {"email"=>["has unverifiable domain"]}

**Comment by ilyapuchka** [comment]
Changing emails in podspec won't have effect as well because the pod spec would need to be published by someone who who is currently listed as author of the speck for what they need to be able to register with trunk to start with.

**Comment by ilyapuchka** [comment]
I suspect the issue is with DNS settings on my domain since I recently moved from DO to GitHub pages + Cloudflare

**Comment by ilyapuchka** [comment]
7.1.0 and 7.1.1 have now been published to trunk 🎉
