### ISSUE TITLE
The ability to specify a container class for auto-injection

### ISSUE THREAD

**Issue by igrekde** [AliSoftware/Dip#25]
Thanks for a great implementation of DI framework in pure swift!

It'd be great to have the ability to configure definitions for auto-injections more detailed, e.g. by specifying a `container class` ([BloodMagic](https://github.com/railsware/BloodMagic#dependency-injection) has a really nice example of this feature).

The use case may be a `TableViewAnimator` protocol, which is implemented by a number of concrete classes. The right one should be chosen based on the container class (zUIViewController` subclass).

**Comment by ilyapuchka** [comment]
Hi, Egor.
Inject also has this feature, called conditional binding, but it's even more powerful there.
I also though about implementing that when was looking at Ninject, but didn't came up with nice use case and clear syntax. Your use case is really nice.

Currently it could be done with tags like this:

```swift
container.register(tag: "\(ViewController.self)") { ViewControllerAnimator() as UIViewControllerAnimatedTransitioning}
container.register(tag: "\(OtherViewController.self)") { OtherViewControllerAnimator() as UIViewControllerAnimatedTransitioning }

//somewhere in ViewController maybe
let animator = container.resolve(tag: "\(self.dynamicType)") as ViewControllerAnimator
```

That will work but I personally don't like how it looks with tags.

So I would +1 for that feature.

#### Implementation 
Regarding implementation we will need two things:
 - add another property to `DefinitionKey` like

```swift
let injectedInType: Any.Type?
```
 - add optional parameter to `resolve` with nil default value:
```swift
let animator = container.resolve(forInstance: self) as UIViewControllerAnimatedTransitioning
```

What bothers me more is the API to define this constraint. There are, the same as with scope, two ways:
  - via argument in `register()` method
  - via chained method on `DefinitionOf`

Also there are few ways we can provide the condition:
- simply with type parameter:
```swift
register(whenInjectedIn: ViewController.self) { Animator() as UIViewControllerAnimatedTransitioning }
```
- using closure syntax:
```swift
register(when: ({ injected in ViewController.self })) { Animator() as UIViewControllerAnimatedTransitioning }
```
- using "context" like in Inject and a boolean condition:

```swift
register(when: ({ context in context.injectedIn is ViewController })) { Animator() as UIViewControllerAnimatedTransitioning }
```

As for me passing condition as argument to `register` causes too many brackets with closure syntax. 
Regarding condition syntax I don't like using `Type.self` too much, though this syntax looks clean.  I like the idea of using "context" to wrap object where the instance is injected, but in our case from one side it looks a bit useless cause we can not check anything but the  type of instance where property is injected to (Ninject thought can switch on method where type is passed as argument). But one the other side using boolean expression is more flexible and I really like that we can use `is` operator here:

```swift
register { Animator() as  UIViewControllerAnimatedTransitioning }.when { $0.injectedIn is ViewController || $0.injectedIn is OtherViewController }
```
Though I didn't test this syntax it looks valid for me.

So, @AliSoftware , how do you feel about that or we recommend to stick to named bindings? If we implement this feature then what syntax do you prefer? Maybe there are another options?

**Comment by AliSoftware** [comment]
I'm not sure I like those solutions, as we won't be able to auto-detect in which class the resolution will happen. That's not like `UIAppearance` for example where ObjC introspection allow it to check in which context it happens.
So in the end to make this feature work, we'll need to specify the type context (`ViewController.self`)  at both ends, both during `register` and `resolve`… which ends up being the exact same behavior and feature as what `tags` provides, so not much would be gained by another new API do the the exact same thing.

Besides, if we were even able to auto-detect the type in which the resolution happen, what about when the resolution isn't happening in a type at all, like at root level or inside a function?
Lastly, I feel like it breaks the very principle of Dependency Injection to make the injection dependent on the container type itself, as it will then make a tightly coupling between the resolved type and the container type. Whereas using (arbitrary) tags will not make that coupling with the `ViewController.self` type.
Dependency injection is also all about tests, and that will make this hard to test because during the app lifetime the resolution will happen in one class in one module but during the unit tests it will be in a different context, leading to a different behavior and result. Whereas once again using arbitrary tags instead would generate the same issue.

**Comment by ilyapuchka** [comment]
I think we would not need to detect injection context manually, it can be just an optional parameter in `resolve()`. Anyhow I tried those variants in Xcode and didn't like where it went to either.

To make tags solution nicer containing classes could define tags as a static property (and maybe even part of some protocol), like this:

```swift
class ViewController: AnimatedTransitionable {
   static var animatorTag: DependencyContainer.Tag {
     return "\(self)"
   }
   ...
   func transitioningDelegate() {
      return transitioningFactory.animatedTransitioning(self)
   }
}

extension DependencyContainer: AnimatedTransitioningFactory {
  func animatedTransitioning(vc: AnimatedTransitionable) -> UIViewControllerAnimatedTransitioningDelegate {
    return try! container.resolve(tag: vc.dynamicType.animatorTag)
  }
}
container.register(tag: ViewController.animatorTag) { Animator() as UIViewControllerAnimatedTransitioning }
```

Other types of conditions could be just a part of factory.

**Comment by AliSoftware** [comment]
My point exactly, the cleanest solution for this would be to do it at the application level, not in Dip itself :wink:

Any new API to provide that will just be the same as what is already possible with a custom tag, and I haven't found a clean way to do that either, The cleanest solution I see is to use the already available solution of tags and, as your example show, to make the container class expose a `DependencyContainer.Tag` itself. Quite [like I did in the sample with the `enum WebService` actually](https://github.com/AliSoftware/Dip/blob/master/SampleApp/DipSampleApp/Providers/SWAPICommon.swift#L16-L20), but on a class instead.

That also keeps some flexibility at the call site, as anyone can use it as they see fit and how it fits best for their need. For people using containers anywhere other than directly inside classes, but in struct and enums and at root, the current solution is still flexible.

In the end, **I don't see the point and would vote against adding another API entry** just for that "container" thing as such a feature already exists with tags, and even with somewhat a cleaner API than anything we could come up — with by doing it at the app level instead of providing it thru Dip, keeping all the flexibility to the user.

**Comment by AliSoftware** [comment]
@igrekde Even if we closed this issue and won't implement it for the aforementioned reasons, I'd still be interested by your feedback to know if the solution proposed by Ilya did fit your needs :wink:
