### ISSUE TITLE
How does type checking work for factory with different arguments?

### ISSUE THREAD

**Issue by onmyway133** [AliSoftware/Dip#28]
Hi, I see that `definitions` is a mapping from `DefinitionKey` to `DefinitionOf`

```
public func registerFactory<T, F>(tag tag: Tag? = nil, scope: ComponentScope, factory: F) -> DefinitionOf<T, F> {
    let key = DefinitionKey(protocolType: T.self, factoryType: F.self, associatedTag: tag)
    let definition = DefinitionOf<T, F>(factory: factory, scope: scope)
    definitions[key] = definition
    return definition
  }
```

But `factory` can be a function that accepts different number of arguments, like

```
public func register<T, Arg1>(tag tag: Tag? = nil, _ scope: ComponentScope = .Prototype, factory: (Arg1) -> T) -> DefinitionOf<T, (Arg1) -> T> {
    return registerFactory(tag: tag, scope: scope, factory: factory) as DefinitionOf<T, (Arg1) -> T>
  }
```

When `resolve`
```
public func resolve<T, F>(tag tag: Tag? = nil, builder: F->T) throws -> T {
    let key = DefinitionKey(protocolType: T.self, factoryType: F.self, associatedTag: tag)
    let nilTagKey = tag.map { _ in DefinitionKey(protocolType: T.self, factoryType: F.self, associatedTag: nil) }

    guard let definition = (self.definitions[key] ?? self.definitions[nilTagKey]) as? DefinitionOf<T, F> else {
      throw DipError.DefinitionNotFound(key)
    }

    let usingKey: DefinitionKey? = definition.scope == .ObjectGraph ? key : nil
    return _resolve(tag, key: usingKey, definition: definition, builder: builder)
  }
```

How does Swift knows the correct `factory`? How does Swift perform type checking here? I mean you just 

```
public func resolve<T, Arg1>(tag tag: Tag? = nil, withArguments arg1: Arg1) throws -> T {
    return try resolve(tag: tag) { (factory: (Arg1) -> T) in factory(arg1) }
  }
```

and it works

**Comment by AliSoftware** [comment]
Answer is in the question ;-)

We store the factory type (`F.self` which is the meta-type, in this case the signature of the factory function) as part of the Definition; so when we resolve we just have to lookup for the definition with the same metatype `F.self` as the implicit factory type given in the resolve arguments.

**Comment by onmyway133** [comment]
If I trick this

```
guard let definition = (self.definitions[key] ?? self.definitions[nilTagKey]) as? DefinitionOf<T, F> else {
      throw DipError.DefinitionNotFound(key)
    }
```

to always return the first definition (assume that the factory in this definition is `() -> T`) in the `definitions`, then this code will fail, right?

```
public func resolve<T, Arg1>(tag tag: Tag? = nil, withArguments arg1: Arg1) throws -> T {
    return try resolve(tag: tag) { (factory: (Arg1) -> T) in factory(arg1) }
  }
```

I mean Swift does not perform type checking here? Given a `DefinitionKey`, and it will return us `DefinitionOf`, and we have to make assumption about the type of `factory` inside, right?

**Comment by ilyapuchka** [comment]
There is a type checking here - `as? DefinitionOf<T, F> `. If `Definition` stored by key will fail to cast to `DefinitionOf<T,F>` then we throw an error. The same happens when you use factories with arguments. The only difference is what `F` is. When no arguments `F` = `()->T`, with one argument `F` = `(Arg1)->T`, for two arguments `F` =`(Arg1, Arg2)->T`.  You can se that in `resolve` method we use a closure that accepts factory and calls it. The type of this wrapping closure is different for different numbers of runtime arguments. This way `resolve` method captures type `F` in parameter `builder: F->T`.

`DefinitionKey` is based on `F` and `T`, so if later you try to resolve type `T` using the same type `F` Dip will find that definition. Using tags you can have few definitions for type `T` with the same type of factory `F` stored by Dip, cause `DefinitionKey` is also based on tag value (see it's `hasValue` property). So given the same tag, `T` and `F` there is no way that we can not find `DefinitionOf<T, F>` if it was ever registered.

Dip fallbacks to factory with no tag and use it as a default factory. Without that it will behave the same way, the difference will be that you will be able to resolve types only using the exact tags that you used to register factories.

**Comment by onmyway133** [comment]
@AliSoftware @ilyapuchka thanks, I got it. Nice work :+1:

**Comment by onmyway133** [comment]
@ilyapuchka you forgot to include this http://ilya.puchka.me/ioc-container-in-swift/
