### ISSUE TITLE
Rename .Singleton scope to .Container

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/Dip#45]
SwInject calls this equivalent scope `Container` and it feels more suited, especially as the term `Singleton` is scary and has a bad reputation especially in the DI world :wink: 

Using `.Container` as the scope better fits the intent, meaning that the instance will be reused as long as the container exists, and will be purged when the container dies, so the reused instance and container have the same lifespan.

**Comment by ilyapuchka** [comment]
Actually there is no convention for naming this thing across different containers. They even name the concept itself differently some times - some call it lifestyle, some - lifecycle, others - scope. 

For example, Autofac call it "single instance", Ninject - "singleton scope", Castle Windsor - "singleton" (it is even used as a default), speaking of cocoa land, Typhoon uses "singleton". All these containers treat this scope the same, as we do. Also in "DI in .Net" book author name this scope as Singleton too (but to be fair he uses Transient instead of Prototype). I was relying on Typhoon way on naming scopes. As I believe it's the most popular DI container for iOS developers (even with Swift, I think).

But, I agree that in some way it makes sense to name it Container to make it clear that it is scoped to container, but in fact I personally don't think it is a good practice to use different containers, usually one is more then enough. We can of course introduce synonymous scope and deprecate Singleton. I just don't think it worths it to bump the version again just for that.

**Comment by AliSoftware** [comment]
Yeah agreed

I just came with that issue because I was explaining a use case to someone on Slack and told the solution was to use the Singleton scope and I was afraid the term would scare them until I explained it.

Someone then tuned in and compared it to SwInject's "Container" scope and it sounded fine to me. But indeed not worth bumping the versio for that and I didn't know so many other DI frameworks used the term Singleton too already

**Comment by ilyapuchka** [comment]
If you will need any help answering questions about Dip somewhere - let me know =)
