### ISSUE TITLE
Rename a few things.

### ISSUE THREAD

**Issue by calebd** [AliSoftware/Dip#48]
Given the [Swift API design guidelines](https://swift.org/documentation/api-design-guidelines/), I would like to propose renaming a couple of things in Dip.

`DependencyContainer(configBlock:)` should be `DependencyContainer(configuration:)` or `DependencyContainer(configurationBlock:)`. The old initializer could be transitioned to a `convenience init` that delegates to the new one, and marked as deprecated. (_Avoid abbreviations._)

`resolve(withArguments:)` should become either `resolve(arguments arguments:)` or `resolveWithArguments(_:)`. The old function should be deprecated and delegate to the new one. (_When the first argument forms part of a prepositional phrase, give it an argument label._)

**Comment by AliSoftware** [comment]
:+1:

**Comment by ilyapuchka** [comment]
Thanks for proposing that, @calebd. Actually I was thinking about renaming something lately too, but not in context of guidelines.

Guidelines are for good of course, but I thinks it can be very arguable how to apply them. 
I don't mean that I'm completely against renaming something, but I'm sure that if we are going to rename things we need to have a deeper look at the guidelines so that we apply consistently and within single release. After all it can be quite a few breaking changes which is not good for users and does not bring any value (of course except of following guideline... that can also change through time). Bumping major version every second release sounds for me like not a very user-friendly thing. Personally I was hoping that we can stop on 4.x =) I think in case of Dip I would personally prefer stability over following guidelines... If we don't need to bump major version and just deprecate stuff - then ok =)

Regarding actual changes. I'm not a native speaker (and far from knowing English well enough :sweat_smile: ) and didn't look carefully through the guideline yet, so I may be completely wrong. And sorry for being too critic! :smiling_imp: I surely don't want you to give up on that proposal, just want to have a best possible result at the end of discussion.

`configBlock` will be most of the time used with trailing closure, I suppose. So maybe from caller side label does not make any difference here at all? From inner (implementation) side I think just `configure` will make calling this block in the implementation more natural: `configure(container)` (like it's said in special instructions part of the guideline)

 With `resolve` you forget that there is an optional `tag` argument on the first place. Even if we don't encounter it, applying "when the first argument forms part of a prepositional phrase, give it an argument label" shouldn't it be "container.resolve(**with**/**using**/**passing**/Arguments:)" like in example "x.removeBoxes(**having**Length: 12)"?
 But maybe tag and arguments represent a single abstraction, so it can be an exception? Or does it "form part of a grammatical phrase" or not? I'm not sure what is the right answer here. The whole `resolve` API currently reads like "resolve tag ... with arguments ... as something" which is not perfect, cause it sounds like we resolve a tag... but we resolve a type... "resolve something with arguments ... tagged ..." reads more natural but it does not fit API design - then we will need to pass type as a method parameter instead of using `as` operator (which I like a lot here): `resolve(Service.self, withArguments: ..., tagged: ...)` - which will cause use of `.self` that I don't like at all... (also that api is not so strongly typed, which can be good or not in different situations).

And what about `register` methods and the fact that `scope` parameter does not have a label at all? Is it ok? When we don't use a tag, then it's fine, but with tag (`register(tag: "", .Singleton)`) it's not so good anymore. Maybe we should also rename `ObjectGraph` scope to something like `Shared` to make `register(.Shared) { ServiceImp() as Service }` feel more natural? I like `ObjectGraph` name more, but in calling context Shared reads more natural. "SharedWithinObjectGraph" as a compromise?
 
If we do rename things though, we may use it as a chance to rename `resolveDependencies` method of `DefinitionOf` too (that is what I was thinking to rename lately, but decided that it does not bring any value), cause it kind of breaks (at least it does not continue it) phrase "register something as something". But I don't have any alternative in mind.

[Naming is hard](http://martinfowler.com/bliki/TwoHardThings.html). Probably there are a lot of other options even in boundaries of that guideline, and we will need to find a compromise. As you can see for me there are more questions then answers here :confused: Let's discuss them here.

**Comment by calebd** [comment]
The Swift guidelines are pretty definitive. Arguments whose name contains a prepositional phrase (with) should be named such that the call site is `verb(argument:)`. That reads as "verb with argument" implicitly. (And in fact, when methods like this are exposed to Objective-C they are exposed as `verbWithArgument:`.)

Cases where a tag is provided would be equally clear. `resolve("", arguments: ...)`. There should likewise be no "with" in that argument name.

**Comment by calebd** [comment]
In your example, the sentence would not be "resolve tag with arguments" but instead "resolve with tag, arguments, ...".

**Comment by calebd** [comment]
(I also tend to think that `tag` should itself be exposed in all calls to `resolve`. `resolve(tag: "", arguments: ...)`

**Comment by ilyapuchka** [comment]
Actually it's good that you mentioned how methods will be exposed to Objective-C. Never though about that, cause never considered using Dip in Objective-C. We definitely need to inspect that too.

**Comment by calebd** [comment]
Dip cannot be used from Objective-C because it uses types that cannot be represented in Objective-C. I used that as an example of a case where the language and its documentation defines clear standards for this sort of thing.

**Comment by ilyapuchka** [comment]
Yeah, really you are right about that, how could I forgot that :sleepy:

**Comment by ilyapuchka** [comment]
I looked through the guideline and came up with the following.

Regarding "arguments" vs "withArguments" I think the current naming is fine.
Definition:
`resolve<T, Arg1, Arg2>(withArguments arguments: Arg1, _ arg2: Arg2, ..., tag: Tag? = nil) -> T`
Usage:
`container.resolve(withArguments: arg, tag: tag) as Service`

We apply _"When the first argument forms part of a prepositional phrase, give it an argument label"_ (what @calebd referenced) But it also says that _"The argument label should normally begin at the preposition"_, which is "with" in that case (for me it is the same as in the example from the guideline - `x.removeBoxes(havingLength: 12)` where "having" is a preposition). I don't see that the guideline says that proposition should be omitted.
The second guideline applied here is _"Prefer to locate parameters with defaults toward the end"_, so we move tag to the end.

Regarding `register` method I also think we need to move `tag` parameter and make it like this:
Definition:
`register<T, Arg1, Arg2>(inScope scope: ComponentScope = .Prototype, tag: Tag? = nil, factory: (Arg1, Arg2) -> T) -> DefinitionOf<T, (Arg1, Arg2) -> T>`
Usage:
`container.register(inScope: .ObjectGraph, tag: tag) { ServiceImp() as Service }`

The other option is to make factory the first argument, I think it will follow the guideline even better, but we will lose trailing closure feature (that will force users to create abstract factories or smth else if factory block is complex enough):
Definition:
`register<T, Arg1, Arg2>(factory: ((Arg1, Arg2) throws -> T), inScope scope: ComponentScope = .Prototype, tag: Tag? = nil) -> DefinitionOf<T, (Arg1, Arg2) throws -> T>`
Usage:
`container.register({ ServiceImp2() as Service }, inScope: .ObjectGraph, tag: "tag")`

The same applies to `registerFactory` method (used only to extend supported number of runtime arguments):
`registerFactory<T, F>(factory: F, inScope scope: ComponentScope, tag: Tag? = nil) -> DefinitionOf<T, F>`
We already use "factory" in the method name to avoid ambiguity, and in context of guideline it also makes sense because the type `F` does not provide any information about nature of that parameter (_"precede each weakly typed parameter with a noun describing its role"_). So we only change the order of arguments to conform to other guidelines.

Regarding `DependencyContainer(configBlock:_)` I lean to `DependencyContainer(configure:_)`
 
Also what about generic arguments naming? Is it clear enough? Should we use `ArgumentTypeN` instead? But then some methods names will become gigantic.

@AliSoftware @calebd what do you think?

**Comment by calebd** [comment]
I think we are overthinking this. Prepositional phrases (or any modifiers really - with, in, having, etc) read weird in Swift code. I think that the methods could be written in such a way that this is not needed. `resolve(tag: "", arguments: ...)` or `resolve(arguments: ...)` at the call site reads better than having "with" in there at all. It is simply not needed.

And moving arguments to the end breaks trailing closures.

**Comment by AliSoftware** [comment]
I do agree that `arguments:` and `scope:` are the names expected by the Guidelines (and not `withArguments:` or `inScope:`)

**Comment by ilyapuchka** [comment]
I've create a pr #105 with some api changes. will be glad to discuss

**Comment by ilyapuchka** [comment]
Resolved with #105
